spring:
  application:
    name: gigzal
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5433/app"
    username: postgres
    password: password
  jpa:
    database: POSTGRESQL
    show-sql: true
  security:
    user:
      name: aman
      password: pass
  banner:
    location: classpath:banner.txt

