spring:
  application:
    name: gigzal
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/app"
    username: postgres
    password: postgres
  jpa:
    database: POSTGRESQL
    show-sql: true


    hibernate:
      ddl-auto: create

  security:
    user:
      name: aman
      password: pass
  banner:
    location: classpath:banner.txt
jwt-token:
  expire-time: 86400000 #  one day


